[theme]
primaryColor = "#6C5CE7"
backgroundColor = "#e6e7ee"
secondaryBackgroundColor = "#e6e7ee"
textColor = "#2c2c3a"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[client]
showErrorDetails = true

